#!/bin/bash

hoststemp="/tmp/hosts-new"
hostnametemp="/tmp/hostname-new"

if [ -n "$1" ]; then
	echo "Changing hostname from $HOSTNAME to $1"
	sed "s/$HOSTNAME/$1/g" /etc/hosts > $hoststemp
	sed "s/$HOSTNAME/$1/g" /etc/hostname > $hostnametemp
	sudo tee /etc/hosts < $hoststemp > /dev/null
	sudo tee /etc/hostname < $hostnametemp > /dev/null
	rm $hoststemp $hostnametemp
else
	echo "Must supply replacement hostname."
fi
