#!/bin/bash

if [ -n "$(which ffmpeg)" ]; then
	convprog="ffmpeg"
elif [ -n "$(which avconv)" ]; then
	convprog="avconv"
else
	echo "ERROR: unable to find ffmpeg or avconv"
	exit 1
fi

sourcedir="$1"
if [ -z "$sourcedir" ]; then
	echo "ERROR: must specify directory"
	exit 1
fi

destdir="$2"
if [ -n "$destdir" ] && [ ! -e "$destdir" ]; then
	echo "ERROR: directory $destdir does not exist"
	exit 1
fi
if [ -n "$destdir" ]; then
	destdir="$destdir/"
fi

echo "creating directory structure for converted files ..."
mkdir "${destdir}conv"
find "$sourcedir" -type d | while read dir; do
	mkdir "${destdir}conv/$dir"
done

tempscript="/tmp/convert-$RANDOM"

echo "converting files from $sourcedir ..."
echo "#!/bin/bash" >> $tempscript
find "$sourcedir" -type f | sort | grep -E ".mp4$|.avi$|.mpg$|.m4v$|.mkv$" | while read srcfile; do
	destfile="${destdir}conv/$(echo $srcfile | rev | colrm 1 4 | rev).mkv"

	hassubtrack="false"
	if [ -n "$(ffprobe $srcfile |& grep Subtitle)" ]; then
		hassubtrack="true"
	fi

	for ext in {srt,sub,idx}; do
		subfile="$(echo $srcfile | sed s/.mkv/.$ext/g)"
		if [ -f "$subfile" ]; then
			echo -e cp "$subfile" "${destdir}conv/${subfile}" | tee /dev/stderr >> $tempscript
		fi
	done

	echo "$srcfile -> $destfile"
	if [ ! -e "$destfile" ]; then
		if [ $hassubtrack == "true" ]; then
			echo -e "$convprog -n -i \"$srcfile\" -c:v libx265 -c:a copy -c:s copy \"$destfile\"" | tee /dev/stderr >> $tempscript
		else
			echo -e "$convprog -n -i \"$srcfile\" -c:v libx265 -c:a copy \"$destfile\"" | tee /dev/stderr >> $tempscript
		fi
	fi
done

bash $tempscript

rm $tempscript
