#!/bin/bash

if [ "$USER" != "root" ]; then
	echo "must run as root"
	exit 1
fi

if [ "$1" == "on" ]; then
	mode="slow"
elif [ "$1" == "off" ]; then
	mode="fast"
else
	echo "must specify on or off"
	exit 1
fi

for cpu in $(ls /sys/devices/system/cpu | grep "^cpu[0-9]"); do
	if [ "$mode" == "slow" ]; then
		speed=$(cat /sys/devices/system/cpu/$cpu/cpufreq/cpuinfo_min_freq)
	else
		speed=$(cat /sys/devices/system/cpu/$cpu/cpufreq/cpuinfo_max_freq)
	fi
	echo "setting $cpu to maximum of $speed Hz"
	echo $speed > /sys/devices/system/cpu/$cpu/cpufreq/scaling_max_freq
done
