#!/bin/bash

DESKTOP=$(which desktop)

COMPUTERS=(
	green.l.bismith.net
	precisix.l.bismith.net
	yogix.l.bismith.net
	lbbtwo.lan)

for COMPUTER in ${COMPUTERS[@]}; do
	if [ "$HOSTNAME" == "$COMPUTER" ]; then
		echo "local:  $COMPUTER"
		$DESKTOP 0 &
	else
		echo "remote: $COMPUTER"
		ssh $COMPUTER "$DESKTOP 0" &
	fi
done

wait
exit $?
