#!/bin/bash

DESKTOP=$(which desktop)

$DESKTOP 0 &
ssh tank.l.bismith.net "$DESKTOP 0" &
ssh nissan.l.bismith.net "$DESKTOP 0" &
ssh precisix.l.bismith.net "$DESKTOP 0" &
ssh yogix.l.bismith.net "$DESKTOP 0" &

wait
echo "All children terminated."
