#!/bin/bash

DESKTOP=$(which desktop)

COMPUTERS=(
	green
	tank
	nissan
	precisix
	yogix)

for COMPUTER in ${COMPUTERS[@]}; do
	if [ "$HOSTNAME" == "$COMPUTER" ]; then
		echo "local:  $COMPUTER"
		$DESKTOP 0 &
	else
		echo "remote: $COMPUTER"
		ssh $COMPUTER.l.bismith.net "$DESKTOP 0" &
	fi
done

wait
exit $?
