#!/bin/bash

DIR=.
GREPSTRING="Stream"
for ARG in $@; do
	if [ "$ARG" == "-d" ]; then
		GREPSTRING="$GREPSTRING|Duration"
	elif [ -d "$ARG" ]; then
		DIR="$ARG"
	else
		echo "ERROR: invalid arg: $ARG"
		exit 1
	fi
done

find -L "$DIR" -type f ! -name "*\.\!ut" | sort | while read FILE; do
	echo "$FILE"
	ffprobe "$FILE" |& grep -v "^\[" | grep -E "$GREPSTRING"
	echo
done
