#!/bin/bash

JUSTFILES="FALSE"
DIR=.
GREPSTRING="Stream"
for ARG in $@; do
	if [ "$ARG" == "-d" ]; then
		GREPSTRING="$GREPSTRING|Duration"
	elif [ -d "$ARG" ]; then
		DIR="$ARG"
	elif [ -f "$ARG" ]; then
		JUSTFILES="TRUE"
		ffprobe "$ARG" |& grep -E "$GREPSTRING"
	else
		echo "ERROR: invalid arg: $ARG"
		exit 1
	fi
done

if [ "$JUSTFILES" == "FALSE" ]; then
	find -L "$DIR" -type f ! -name "*\.\!ut" | sort | while read FILE; do
		echo "$FILE"
		ffprobe "$FILE" |& grep -E "$GREPSTRING"
		echo
	done
fi

find -L "$DIR" -type f ! -name "*\.\!ut" | sort | while read FILE; do
	echo "$FILE"
	ffprobe "$FILE" |& grep -v "^\[" | grep -E "$GREPSTRING"
	echo
done

