#!/bin/bash

find -name "Imgur Album*.zip" | while read archive; do
	dirname=$(echo $archive | colrm 1 2 | rev | colrm 1 12 | rev | tr ' ' '-')
	echo "extracting $archive to $dirname"
	mkdir "$dirname"
	7za x -o"$dirname" "$archive" && rm "$archive"
done
