#!/usr/bin/env python3

import sys

class SRTTimeMultiplier:

	def __init__(self, src):
		self.src = src

	def multiply_time(self, time, factor):
		spl = time.replace(",", ".").split(":")
		s = 60 * (60 * int(spl[0]) + int(spl[1])) + float(spl[2])
		s *= factor
		h = s // (60 * 60)
		s -= h * (60 * 60)
		m = s // 60
		s -= m * 60
		time = "{}:{}:{:.3f}".format(int(h), int(m), round(s, 3))
		return time

	def multiply_times(self, line, factor):
		times = line.split(" --> ")
		return " --> ".join(self.multiply_time(t, factor) for t in times)

	def multiply(self, factor):
		out = ""
		for line in self.src.split("\n"):
			if "-->" in line:
				out += self.multiply_times(line, factor)
			else:
				out += line
			out += "\n"
		return out

def main():
	if len(sys.argv) <= 1:
		print("ERROR: must specify .srt file")
		exit(1)
	with open(sys.argv[1]) as infile:
		src = infile.read()
	subfixer = SRTTimeMultiplier(src)
	fixed = subfixer.multiply(100)
	for line in fixed.split("\n"):
		print("fixed:", line)

if __name__ == "__main__":
	main()
