#!/usr/bin/env python3

import sys

class SRTTimeMultiplier:

	def __init__(self, src):
		self.src = src

	def process_chunk(self, chunk):
		lines = chunk.split("\n")
		if not lines[0]:
			return "BLANKLINE!\n"
		try:
			chunknum = int(lines[0])
		except:
			return "bad string: {}".format(lines[0])
		return "chunknum: {}\n".format(chunknum)

	def multiply(self, factor):
		out = ""
		for chunk in self.src.split("\n\n"):
			out += self.process_chunk(chunk.strip())
		return out

def main():
	if len(sys.argv) <= 1:
		print("ERROR: must specify .srt file")
		exit(1)
	with open(sys.argv[1]) as infile:
		src = infile.read()
	subfixer = SRTTimeMultiplier(src)
	fixed = subfixer.multiply(1000)
	for line in fixed.split("\n"):
		print("fixed:", line)

if __name__ == "__main__":
	main()
