#!/bin/bash

user=$(whoami)

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
	echo "usage: mountdir [servername] [serverdir] [mountdir]"
	echo "example: mountdir vps.bismith.net /home/bismith /mnt/bismith"
else
	server="$1"
	serverdir="$2"
	mountdir="$3"

	if [ $(stat -c "%u" $mountdir) == $(id -u $user) ]; then
		echo "$mountdir already mounted, owned by $user"
	else
		echo "mounting $mountdir ($server:$dironserver) ..."
		sudo sshfs ${user}@${server}:$serverdir $mountdir -o uid=$(id -u $user),gid=$(id -g $user),allow_other,IdentityFile=/home/$user/.ssh/id_rsa
	fi
fi
