#!/bin/bash

# get containing directory of script
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
dir=$(dirname $(readlink -f $DIR/$(basename "$0")))


# check dependencies

if [ -z "$(which acd_cli)" ]; then
	if [ -z "$(which pip3)" ]; then
		sudo apt install python3 python3-pip
	fi
	sudo pip3 install --upgrade --pre acdcli
fi
if [ -z "$(which realpath)" ]; then
	sudo apt install realpath
fi


# get mount points

ACDMOUNTPOINT="$1"
if [ -z "$ACDMOUNTPOINT" ]; then
	ACDMOUNTPOINT=/mnt/acd
	if [ ! -d "$ACDMOUNTPOINT" ]; then
		sudo mkdir "$ACDMOUNTPOINT" 2> /dev/null
	fi
fi
sudo chown $(id -u):$(id -g) "$ACDMOUNTPOINT" 2> /dev/null
echo "acd:   $ACDMOUNTPOINT"


# check if acd_cli is properly set up

if [ ! -e $HOME/.cache/acd_cli/oauth_data ]; then
	echo "ERROR: acd_cli needs to be initlialized"
	acd_cli init
	acd_cli sync
fi


# do the mounting

if [ -z "$(df | grep -E $ACDMOUNTPOINT$)" ]; then
	echo "mounting acd to $ACDMOUNTPOINT"
	if [ ! -d acd ]; then
		mkdir "$ACDMOUNTPOINT"
	fi
	acd_cli mount "$ACDMOUNTPOINT"
else
	echo "acd already mounted"
fi
