#!/bin/bash

file="$1"

if [ ! -f "$file" ]; then
	if [ ! -d /mnt/iso ]; then
		sudo mkdir /mnt/iso
	fi
	sudo mount -o loop,ro,uid=$(id -u bismith),gid=$(id -g bismith) "$1" /mnt/iso
else
	if [ -n "$file" ]; then
		echo "file not found: $file"
	else
		echo "must specify iso file to mount"
	fi
fi
