#!/bin/bash

mountdir="/mnt/ramdisk"

size=1048
if [ -n "$1" ]; then
	size="$1"
fi

if [ ! -d $mountdir ]; then
	sudo mkdir $mountdir
fi

# mounts yoga share
owner=$(stat -c "%u" $mountdir)
if [ $(id -u) == $owner ]; then
	echo "$mountdir already mounted, owned by $owner"
else
	echo "mounting $mountdir with $size MB..."
	sudo mount -t tmpfs -o size=${size}m tmpfs $mountdir -o uid=$(id -u),gid=$(id -g)
fi
