#!/bin/bash

MOUNTDIR="/mnt/ramdisk"

PREFIX=m
SIZE=1048
if [ -n "$1" ]; then
	SIZE="$1"
	END=$(echo $SIZE | rev | colrm 2 | tr '[:upper:]' '[:lower:]')
	if [ "$END" == "m" ]; then
		PREFIX=m
		SIZE=$(echo $SIZE | rev | colrm 1 1 | rev)
	elif [ "$END" == "g" ]; then
		PREFIX=g
		SIZE=$(echo $SIZE | rev | colrm 1 1 | rev)
	elif [ "$END" == "t" ]; then
		# one day ...
		PREFIX=t
		SIZE=$(echo $SIZE | rev | colrm 1 1 | rev)
	fi
fi
PREFIX_UPPER=$(echo $PREFIX | tr '[:lower:]' '[:upper:]')

if [ ! -d $MOUNTDIR ]; then
	sudo mkdir $MOUNTDIR
fi

OWNER=$(stat -c "%u" $MOUNTDIR)
if [ $(id -u) == $OWNER ]; then
	echo "$MOUNTDIR already mounted, owned by $OWNER"
else
	echo "mounting $MOUNTDIR with $SIZE ${PREFIX_UPPER}B..."
	sudo mount -t tmpfs -o size=${SIZE}${PREFIX} tmpfs $MOUNTDIR -o uid=$(id -u),gid=$(id -g)
	df -hT /mnt/ramdisk
fi
