#!/bin/bash

mountdir="/mnt/iso"

file="$1"

if [ -e "$file" ]; then
	if [ ! -d "$mountdir" ]; then
		sudo mkdir "$mountdir"
	fi
	sudo mount -o loop,ro,uid=$(id -u),gid=$(id -g) "$file" "$mountdir"
else
	if [ -n "$file" ]; then
		echo "file not found: $file"
	else
		echo "must specify iso file to mount"
	fi
fi
