#!/bin/bash


HAS_HOME=$([ -n "$(ip route | grep ^10\\.0\\.0\\.0/16)" ] && echo TRUE || echo FALSE)
HAS_SECONDARY=$([ -n "$(ip route | grep ^172\\.16\\.1\\.0/24)" ] && echo TRUE || echo FALSE)
HAS_VPN=$([ -n "$(ip route | grep ^10\\.48\\.0\\.0/16)" ] && echo TRUE || echo FALSE)

# echo "HAS_HOME:      $HAS_HOME"
# echo "HAS_SECONDARY: $HAS_SECONDARY"
# echo "HAS_VPN:       $HAS_VPN"


if [ "$HAS_SECONDARY" == "TRUE" ]; then
	echo "Using secondary LAN, subnet 172.16.1.0/24"
	GREEN=172.16.1.1
	TANK=172.16.1.2
	NISSAN=172.16.1.3
elif [ "$HAS_HOME" == "TRUE" ]; then
	echo "Using primary LAN, subnet 10.0.0.0/16"
	GREEN=10.0.1.100
	TANK=10.0.1.101
	NISSAN=10.0.1.102
elif [ "$HAS_VPN" == "TRUE" ]; then
	echo "Using VPN, subnet 10.48.0.0/16"
	GREEN=10.48.1.100
	TANK=10.48.1.101
	NISSAN=10.48.1.102
else
	echo "ERROR: Unable to find appropriate network connectivity for mounting remote directories." 1>&2
	exit 1
fi


if [ "$HOSTNAME" != "green" ]; then
	mountssh-readonly $GREEN /tank /mnt/tank
	mountssh-readonly $GREEN /store /mnt/store
else
	echo "Skipping $HOSTNAME (that's you!)"
fi

if [ "$HOSTNAME" != "tank" ]; then
	mountssh-readonly $TANK /ssd /mnt/tank-ssd
	mountssh-readonly $TANK /intel /mnt/tank-intel
else
	echo "Skipping $HOSTNAME (that's you!)"
fi

if [ "$HOSTNAME" != "nissan" ]; then
	mountssh-readonly $NISSAN /internal /mnt/nissan-internal
else
	echo "Skipping $HOSTNAME (that's you!)"
fi
