#!/bin/bash

mountdir="/mnt/iso"

file="$1"

if [ ! -f "$file" ]; then
	if [ ! -d "$mountdir" ]; then
		sudo mkdir "$mountdir"
	fi
	sudo mount -o loop,ro,uid=$(id -u),gid=$(id -g) "$1" "$mountdir"
else
	if [ -n "$file" ]; then
		echo "file not found: $file"
	else
		echo "must specify iso file to mount"
	fi
fi
