#!/bin/bash

if [ "$1" == "stop" ] || [ "$1" == "off" ]; then
	grep -v phone-home < /etc/rc.local > /tmp/rc-local-temp
	sudo mv /tmp/rc-local-temp /etc/rc.local
	sudo chmod 755 /etc/rc.local

	echo "killing phone-home"
	sudo pkill -kill phone-home
elif [ "$1" == "-l" ] || [ "$1" == "--listen" ]; then
	echo "listening ..."
	nc -l 8888
	while [ $? == 0 ]; do
		!!
	done
else
	while [ 1 ]; do
		for interface in $(ls /sys/class/net | grep -v lo); do
			address=$(ip addr show | grep $interface | grep inet | tr '/' ' ' | awk '{print $2}')
			echo "$HOSTNAME :: $interface :: $address" | nc vps.bismith.net 8888
		done
		sleep 15
	done
fi
