#!/bin/bash

get_display() {
	if [ -z "$DISPLAY" ]; then
		export DISPLAY=:0
	fi
}

if [ -z "$1" ]; then
	1>&2 echo "must specify file"
	exit 1
elif [ ! -e "$1" ]; then
	1>&2 echo "file not found: $1"
	exit 1
fi

if [ -n "$(which omxplayer)" ]; then
	omxplayer -b -o hdmi "$1"
elif [ -n "$(which vlc)" ]; then
	set_display
	vlc -f --play-and-exit --file-caching=10000 "$1"
elif [ -n "$(which mplayer)" ]; then
	set_display
	mplayer -fs "$1"
else
	1>&2 echo "no suitable player found"
	exit 2
fi
