#!/bin/bash

trap exitcleanly SIGINT
function exitcleanly() {
	rm $playlist $script
	exit 0
}

rand="$RANDOM"

playlist="/run/shm/playall-playlist.m3u"
script="/run/shm/playall-script.sh"
#playlist="/run/shm/playall-playlist-$rand.m3u"
#script="/run/shm/playall-script-$rand.sh"
rm -f $playlist $script

echo "loading playlist ..."
input="$1"
if [ -z "$input" ]; then
	input="."
fi
if [ -d "$input" ]; then
	find "$input" -type f | grep -E "avi$|mp4$|mkv$" | sort > $playlist
else
	cat "$input" > $playlist
fi

echo "playlist files ..."
echo -e "#/bin/bash\n" > $script
cat $playlist | while read line; do
	echo -e "\nclear" >> $script
	echo -e "echo \"$line\"" >> $script
	echo -e "play \"$line\"" >> $script
done

bash $script

exitcleanly
