#!/bin/bash

interface="wlan0"
pingaddr="google.com"
flagfile="/run/shm/rpi-wifi-reconnect.flag"

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT
function ctrl_c() {
	echo
	echo "deleting $flagfile ..."
	rm "$flagfile"
	exit 0
}

if [ -z "$(ls /sys/class/net | grep $interface)" ]; then
	echo "ERROR: the specified interface $interface doesn't seem to exist"
	exit 1
fi

# if this file exists, then this script is already running (hopefully)
if [ -f "$flagfile" ]; then
	echo "ERROR: this script is already running on this system"
	echo "If this isn't true, you should manually delete this file:"
	echo "$flagfile"
	exit 1
else
	echo "pid:$$" >> $flagfile
fi

echo "running with pid $$"
while true; do
	ping -c 1 $pingaddr &> /dev/null
	if [ "$?" != "0" ]; then
		echo "could not find $pingaddr at $(date)"
		echo "attempting to reconnect wireless interface $interface ..."
		echo sudo ifup --force $interface
	fi
	sleep 60
	if [ -f "$flagfile" ]; then
		echo "$flagfile has been deleted, exiting ..."
		exit 0
	fi
done
