#!/bin/bash

tempscript="/tmp/playall-$RANDOM"

printf "#!/bin/bash\n\n" >> $tempscript

find "$1" -type f | grep -E "mp4$|m4v$|mkv$|avi$|mpg$" | sort $2 | while read line; do
	echo "clear" >> $tempscript
	echo -e "echo \"$line\"" >> $tempscript
	echo -e "omxplayer -b -o hdmi \"$line\"" >> $tempscript
	echo -e "echo\n" >> $tempscript
done

bash $tempscript

rm $tempscript
