#!/bin/bash


function remove_ip_addr {
	ADDRESS=$1
	DEVICE=$2
	sudo ip addr del $ADDRESS dev $DEVICE
}

function set_ip_addr {
	ADDRESS=$1
	DEVICE=$2
	CURRENT_IP=$(ip addr show dev $DEVICE | grep inet | awk '{print $2}')
	if [ "$ADDRESS" == "$CURRENT_IP" ]; then
		echo "device $DEVICE already has target IP $ADDRESS"
		return
	fi
	if [ -n "$CURRENT_IP" ]; then
		echo "device $DEVICE already has IP $CURRENT_IP, removing ..."
		remove_ip_addr $ADDRESS $DEVICE
	fi
	sudo ip link set $DEVICE up
	sudo ip addr add $ADDRESS dev $DEVICE
	CURRENT_IP=$(ip addr show dev $DEVICE | grep inet | awk '{print $2}')
	echo "The IP address for device $DEVICE is now $CURRENT_IP"
}

if [ "green" == "$HOSTNAME" ]; then
	echo "setting IP addresses for green"
	set_ip_addr 172.16.1.1/24 enp4s0f0
	set_ip_addr 172.16.2.1/24 enp4s0f1
fi
if [ "tank" == "$HOSTNAME" ]; then
	echo "setting IP addresses for tank"
	set_ip_addr 172.16.1.2/24 enp4s0f0
	set_ip_addr 172.16.2.2/24 enp4s0f1
fi
if [ "nissan" == "$HOSTNAME" ]; then
	echo "setting IP addresses for nissan"
	set_ip_addr 172.16.1.3/24 enp4s0f0
	set_ip_addr 172.16.2.3/24 enp4s0f1
fi
