#!/bin/bash

cd ~/Pictures/Wallpaper

if [ -n "$1" ]; then
	if [ "$1" == "-r" ]; then
		file="$(ls | sort -R | head -n 1)"
	else
		file="$1"
	fi
else
	file="$(ls -t | head -n 1)"
fi

echo "setting $file as background image"

if [ -n "$(which set-wallpaper)" ]; then
	set-wallpaper "$file"
else
	gsettings set org.gnome.desktop.background picture-uri "file://$(readlink -f file)"
fi
