#!/bin/bash

INTERFACE=$1
if [ -z "$INTERFACE" ]; then
	INTERFACE=$(ip route show default | head -n 1 | awk '{print $5}')
fi
echo "Using interface $INTERFACE ..."

speedometer -r $INTERFACE -t $INTERFACE
