#!/bin/bash

INTERFACE=$1

if [ -z "$INTERFACE" ]; then
	INTERFACE=$(ifconfig | grep -v "^ " | awk '{print $1}' | grep ^e)
fi
if [ -z "$INTERFACE" ]; then
	INTERFACE=$(ifconfig | grep -v "^ " | awk '{print $1}' | grep ^w)
fi
echo "Using interface $INTERFACE ..."

speedometer -r $INTERFACE -t $INTERFACE
