#!/bin/bash
wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip
wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test100.zip
wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip
