#!/bin/bash

if [ -n "$(which isconfig)" ]; then
	if [ -z "$INTERFACE" ]; then
		INTERFACE=$(ifconfig | grep -v "^ " | awk '{print $1}' | grep ^w)
	fi
	iwconfig $INTERFACE | tr '"' '\n' | head -n 2 | tail -n 1
fi
