#!/bin/bash

sudo apt update \
	&& sudo apt upgrade -y \
	&& sudo apt dist-upgrade -y \
	&& sudo apt autoremove -y \
	&& echo DONE

if [ $? -ne 0 ]; then
	echo "ERROR: update did not run successfully" 1>&2
	exit 1
fi

if [ -e /var/run/reboot-required ]; then
	echo
	echo "This machine ($HOSTNAME) must be rebooted in order to complete the update process."
	echo
	echo "*** System restart required ***"
	echo
fi
