#!/bin/bash

REMOTEPROG=mosh

USER=$(whoami)
if [ -n "$1" ]; then
	MACHINE="$1"
	MOUNT="false"
else
	MACHINE="the-professor"
	MOUNT="true"
fi

if [ "$MOUNT" == "true" ]; then
	if [ -z "$(df | grep utcs)" ]; then
		mountssh $MACHINE.cs.utexas.edu /v/filer4b/v38q001/$USER /mnt/utcs
	fi
	if [ -z "$(df | grep utcs-$MACHINE)" ]; then
		mountssh $MACHINE.cs.utexas.edu /var/local /mnt/utcs-$MACHINE
	fi
fi

$REMOTEPROG $MACHINE.cs.utexas.edu

if [ "$MOUNT" == "true" ]; then
	if [ -z "$(df /mnt/utcs)" ]; then
		echo "unmounting /mnt/utcs ... "
		sudo umount /mnt/utcs && sudo rmdir /mnt/utcs
	fi
	if [ -z "$(df /mnt/utcs-$MACHINE)" ]; then
		echo "unmountint /mnt/utcs-$MACHINE ... "
		sudo umount /mnt/utcs-$MACHINE && sudo rmdir /mnt/utcs-$MACHINE
	fi
fi
