#!/bin/bash

IFNAME=$(ifconfig | grep -v "^ " | awk '{print $1}' | grep ^e)
if [ -z "$IFNAME" ]; then
	IFNAME=$(ifconfig | grep -v "^ " | awk '{print $1}' | grep ^w)
fi
if [ -n "$IFNAME" ]; then
	sudo etherwake -i $IFNAME 5C:26:0A:31:DF:37
else
	echo "unable to determine network interface"
fi
