#!/bin/bash

IFNAME=$(ifconfig | grep -v "^ " | awk '{print $1}' | grep ^e)
if [ -z "$IFNAME" ]; then
	IFNAME=$(ifconfig | grep -v "^ " | awk '{print $1}' | grep ^w)
fi
if [ -n "$IFNAME" ]; then
	sudo etherwake -i $IFNAME 1C:1B:0D:96:C0:CC
else
	echo "unable to determine network interface"
fi
