#!/bin/bash

MAC=$1

IFNAME=$(ip r | grep ^default | awk '{print $5}')

if [ -n "$IFNAME" ]; then
	echo etherwake -i $IFNAME $MAC
	sudo etherwake -i $IFNAME $MAC
else
	echo "unable to determine network interface"
	exit 1
fi
