#!/bin/bash

IFNAME=$(ifconfig | grep -v "^ " | awk '{print $1}' | grep ^e)
if [ -z "$IFNAME" ]; then
	IFNAME=$(ifconfig | grep -v "^ " | awk '{print $1}' | grep ^w)
fi
if [ -n "$IFNAME" ]; then
	sudo etherwake -i $IFNAME 4C:CC:6A:89:15:FD
else
	echo "unable to determine network interface"
fi
