#!/bin/bash

if [ -z "$(which xdotool)" ]; then
	echo "ERROR: unable to find xdotool. Is it installed?" 1>&2
	exit 1
fi

if [ -z "$DISPLAY" ]; then
	export DISPLAY=:0.0
else
	echo "display already set: $DISPLAY"
fi

LENGTH=1
DELAY=10

while true; do
	for ANGLE in 0 90 180 270; do
		echo "$(date) :: moving mouse [angle=$ANGLE,length=$LENGTH]"
		xdotool mousemove_relative --polar $ANGLE $LENGTH
		sleep $DELAY
	done
	#sleep $DELAY
done
