#!/bin/bash

CHANNEL="$1"
if [ -z "$CHANNEL" ]; then
	echo "ERROR: must specify channel"
	exit 1
fi

youtube-dl -i -f 266+140 -o "%(upload_date)s - %(title)s - %(id)s.%(ext)s" "https://www.youtube.com/channel/${CHANNEL}/videos"
